import logo from '../assets/logo.png';
import classes from './Header.module.css'; // use CSS modules.

//CSS modules are a way to scope CSS to a specific component, preventing styles from leaking out and affecting other parts of the application. When you import a CSS module, you get an object where the keys are the class names defined in the CSS file and the values are unique class names generated by the build tool. This allows you to use the styles in your component without worrying about naming conflicts with other styles in the application.
//CSS classes are scoped to the component which imports them when usingg CSS modules. 

export default function Header() {
  return (
    <header>
      <img src={logo} alt="A canvas" />
      <h1>ReactArt</h1>
      {/* Use CSS modules for styling, a unique class name is generated for each class by the build tool. */}
      <p className={classes.paragraph}>A community of artists and art-lovers.</p>
    </header>
  );
}
